# Generated by Django 5.2.4 on 2025-07-30 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0002_subscription_anime'),
        ('app_myanimes', '0002_myanime_delete_anime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='anime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_myanimes.myanime'),
        ),
    ]
