# Generated by Django 5.2.4 on 2025-07-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0003_alter_subscription_anime'),
        ('app_myanimes', '0002_myanime_delete_anime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='anime',
        ),
        migrations.AddField(
            model_name='subscription',
            name='anime',
            field=models.ManyToManyField(to='app_myanimes.myanime'),
        ),
    ]
