# Generated by Django 5.2.4 on 2025-07-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_myanimes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='myanime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('story', models.CharField(max_length=60)),
                ('score', models.IntegerField()),
                ('status', models.BooleanField(null=True)),
                ('Date_post', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Anime',
        ),
    ]
