# Generated by Django 5.2.4 on 2025-08-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_myanimes', '0002_myanime_delete_anime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myanime',
            name='story',
            field=models.TextField(blank=True, null=True),
        ),
    ]
