# Generated by Django 5.2.5 on 2025-09-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0004_profile_bio_profile_favorite_genres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='state',
            field=models.CharField(choices=[('watching', 'Watching'), ('finished', 'Finished')], default='watching', max_length=20),
        ),
    ]
