# Generated by Django 5.2.4 on 2025-09-05 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0005_comment'),
        ('app_users', '0005_post_name_post_score_post_state'),
    ]

    operations = [
    ]
